import { ForwardRefExoticComponent, MemoExoticComponent, RefAttributes, SVGProps } from 'react'

import { SvgWrapper } from '@/assets/icons/wrapper'
import { Meta, StoryObj } from '@storybook/react'

import {
  ArrowBackOutline,
  ArrowForwardOutline,
  ArrowIosBack,
  ArrowIosBackOutline,
  ArrowIosDownOutline,
  ArrowIosForward,
  ArrowIosForwardOutline,
  ArrowIosUp,
  Block,
  Bookmark,
  BookmarkOutline,
  Calendar,
  CalendarOutline,
  Close,
  CloseOutline,
  ColorPaletteOutline,
  Copy,
  CopyOutline,
  CreditCard,
  CreditCardOutline,
  Edit2,
  Edit2Outline,
  Email,
  EmailOutline,
  Expand,
  ExpandOutline,
  Eye,
  EyeOff,
  EyeOffOutline,
  EyeOutline,
  FacebookSvgrepoCom11,
  FunnelOutline1,
  GithubSvgrepoCom31,
  GoogleSvgrepoCom1,
  Heart,
  HeartOutline,
  Home,
  HomeOutline,
  Image,
  ImageOutline,
  Layers,
  LayersOutline,
  LogOut,
  LogOutOutline,
  Maximize,
  MaximizeOutline,
  MenuOutline,
  MessageCircle,
  MessageCircleOutline,
  Mic,
  MicOutline,
  MoreHorizontal,
  MoreHorizontalOutline,
  MoreVerticalOutline,
  Paid,
  PaperPlane,
  PaperPlaneOutline,
  PauseCircle,
  PauseCircleOutline,
  PaypalSvgrepoCom4,
  Person,
  PersonAdd,
  PersonAddOutline,
  PersonOutline,
  PersonRemove,
  PersonRemoveOutline,
  Pin,
  PinOutline,
  PlayCircle,
  PlayCircleOutline,
  PlusCircle,
  PlusCircleOutline,
  PlusSquare,
  PlusSquareOutline,
  RadioButtonChecked,
  RadioButtonUnchecked,
  Recaptchalogo1,
  Search,
  SearchOutline,
  Settings,
  SettingsOutline,
  Star,
  StarOutline,
  StripeSvgrepoCom4,
  Trash,
  TrashOutline,
  TrendingUp,
  TrendingUpOutline,
} from './components'

const SvgComp: MemoExoticComponent<
  ForwardRefExoticComponent<Omit<SVGProps<SVGSVGElement>, 'ref'> & RefAttributes<SVGSVGElement>>
>[] = [
  ArrowBackOutline,
  ArrowForwardOutline,
  ArrowIosBack,
  ArrowIosBackOutline,
  ArrowIosDownOutline,
  ArrowIosForward,
  ArrowIosForwardOutline,
  ArrowIosUp,
  Block,
  Bookmark,
  BookmarkOutline,
  Calendar,
  CalendarOutline,
  Close,
  CloseOutline,
  ColorPaletteOutline,
  Copy,
  CopyOutline,
  CreditCard,
  CreditCardOutline,
  Edit2,
  Edit2Outline,
  Email,
  EmailOutline,
  Expand,
  ExpandOutline,
  Eye,
  EyeOff,
  EyeOffOutline,
  EyeOutline,
  FacebookSvgrepoCom11,
  FunnelOutline1,
  GithubSvgrepoCom31,
  GoogleSvgrepoCom1,
  Heart,
  HeartOutline,
  Home,
  HomeOutline,
  Image,
  ImageOutline,
  Layers,
  LayersOutline,
  LogOut,
  LogOutOutline,
  Maximize,
  MaximizeOutline,
  MenuOutline,
  MessageCircle,
  MessageCircleOutline,
  Mic,
  MicOutline,
  MoreHorizontal,
  MoreHorizontalOutline,
  MoreVerticalOutline,
  Paid,
  PaperPlane,
  PaperPlaneOutline,
  PauseCircle,
  PauseCircleOutline,
  PaypalSvgrepoCom4,
  Person,
  PersonAdd,
  PersonAddOutline,
  PersonOutline,
  PersonRemove,
  PersonRemoveOutline,
  Pin,
  PinOutline,
  PlayCircle,
  PlayCircleOutline,
  PlusCircle,
  PlusCircleOutline,
  PlusSquare,
  PlusSquareOutline,
  RadioButtonChecked,
  RadioButtonUnchecked,
  Recaptchalogo1,
  Search,
  SearchOutline,
  Settings,
  SettingsOutline,
  Star,
  StarOutline,
  StripeSvgrepoCom4,
  Trash,
  TrashOutline,
  TrendingUp,
  TrendingUpOutline,
]

const meta: Meta<typeof SvgWrapper> = {
  component: SvgWrapper,
  parameters: {
    category: 'stories',
    content: 'IconComponentsMap',
  },

  tags: ['autodocs'],
  title: 'Components/SvgComp',
} satisfies Meta<typeof SvgWrapper>

export default meta
type Story = StoryObj<typeof meta>

export const AllComponents: Story = {
  render: () => {
    return (
      <>
        {SvgComp.map((Component, index) => (
          <SvgWrapper key={index} wrapper={'button'}>
            <Component
              style={{
                border: '0.5px solid',
                borderRadius: '5px',
                boxShadow: 'rgb(0 77 152) 0px 0px 5px 2px',
                margin: '10px',
                padding: '5px',
                width: '28px',
              }}
            />
          </SvgWrapper>
        ))}
      </>
    )
  },
}
